import { resolve } from "node:path";
import type { Approval, CompiledPlan, NativePlan, OperatorAuthority, SpecDocument } from "./types";
import { atomicWrite, digest, now, object, parseObject, PLAN_PATH, readJson, readText, safePath, SPEC_PATH, stable, stop, WORKFLOW_DIR, writeJson } from "./storage";
import { validateNativePlan } from "./validation";
import { validateAuthority } from "./authority";
export function planDigest(plan: NativePlan): string { const { created_at: _, ...content } = plan; return digest(content); }
export function specFromPlan(plan: NativePlan, approved = false): SpecDocument {
    return {
        schema_version: "wringer.spec.v1", approved, title: plan.title, intent: plan.intent,
        criteria: plan.requirements.map(({ id, title, required, human, guidance }) => ({ id, title, required, human, ...(guidance ? { guidance } : {}) })),
        open_questions: plan.questions.map(({ id, question, required, answer }) => ({ id, question, required, answer: answer ?? "" })),
        tasks: plan.tasks.map(({ id, brief, dir, objective }) => ({ id, brief, dir, objective })), gates: [],
    };
}
function gateSidecar(plan: NativePlan) {
    return { schema_version: "wringer.gatespec.v2", ...(plan.gates.length ? { gates: plan.gates } : {}), ...(Object.keys(plan.show).length ? { show: plan.show } : {}) };
}
export async function loadNativePlan(repo: string, required = true): Promise<NativePlan | null> {
    try {
        const raw = await readJson<unknown>(repo, PLAN_PATH);
        if (raw === null)
            return required ? stop(repo, "plan-missing", "There is no drafted plan on record.", `wring spec ${JSON.stringify(`${WORKFLOW_DIR}/source.md`)} --send`) : null;
        const plan = validateNativePlan(raw);
        const ledgerPath = `${WORKFLOW_DIR}/requirements/${plan.source_sha256}.json`;
        const ledger = await readJson<Record<string, unknown>>(repo, ledgerPath);
        if (!ledger || digest(ledger) !== plan.ledger_sha256)
            throw new Error(`Immutable requirement ledger ${ledgerPath} is absent or changed`);
        if (ledger.original_source !== plan.intent || digest(plan.intent) !== plan.source_sha256)
            throw new Error("Plan's original source differs from the immutable ledger");
        if (stable(ledger.requirements) !== stable(plan.requirements))
            throw new Error("Plan requirements differ from the immutable ledger");
        return plan;
    }
    catch (error) {
        return stop(repo, "plan-unreadable", (error as Error).message, "wring explain");
    }
}
export async function loadSpec(repo: string): Promise<SpecDocument> {
    const text = await readText(repo, SPEC_PATH);
    if (text === null)
        return stop(repo, "spec-missing", "No wringer.spec.yaml exists.", `wring spec ${JSON.stringify(`${WORKFLOW_DIR}/source.md`)} --send`);
    try {
        const spec = parseObject(text, SPEC_PATH);
        if (spec.schema_version !== "wringer.spec.v1" || typeof spec.approved !== "boolean" || !Array.isArray(spec.criteria) || !Array.isArray(spec.tasks))
            throw new Error("Spec has an unsupported or malformed shape");
        return spec as unknown as SpecDocument;
    }
    catch (error) {
        return stop(repo, "spec-unreadable", (error as Error).message, "wring explain");
    }
}
export async function savePlan(repo: string, plan: NativePlan, options: {
    resolveRevision?: boolean;
} = {}) {
    const approval = await readJson<Approval>(repo, `${WORKFLOW_DIR}/approval.json`);
    const approved = !!approval && approval.schema_version === "wringer.workflow-approval.v1" && approval.digest === planDigest(plan);
    const existing = await readText(repo, SPEC_PATH);
    const owned = await readJson<{
        spec_sha256?: string;
    }>(repo, `${WORKFLOW_DIR}/owned-spec.json`);
    if (existing !== null && (!owned || owned.spec_sha256 !== digest(existing)))
        return stop(repo, "spec-edited-outside-workflow", "wringer.spec.yaml has an operator edit or is not owned by this workflow. It will not be overwritten. Import it deliberately or move it aside before drafting.", "wring spec --help");
    const existingGates = await readText(repo, "wringer.gates.yaml");
    const ownedGates = await readJson<{
        sha256: string;
    }>(repo, `${WORKFLOW_DIR}/owned-gates.json`);
    if (existingGates !== null && (!ownedGates || ownedGates.sha256 !== digest(existingGates)))
        return stop(repo, "gates-edited-outside-workflow", "wringer.gates.yaml has an operator edit or was not generated by this workflow. It will not be overwritten.", "wring plan --json");
    await writeJson(repo, PLAN_PATH, plan);
    await writeSpec(repo, specFromPlan(plan, approved));
    const gateText = JSON.stringify(gateSidecar(plan), null, 2) + "\n";
    await atomicWrite(repo, "wringer.gates.yaml", gateText);
    await writeJson(repo, `${WORKFLOW_DIR}/owned-gates.json`, { sha256: digest(gateText) });
    if (options.resolveRevision)
        await writeJson(repo, `${WORKFLOW_DIR}/revision-needed.json`, { status: "resolved", plan_digest: planDigest(plan), at: now() });
}
async function writeSpec(repo: string, spec: SpecDocument) {
    const text = JSON.stringify(spec, null, 2) + "\n";
    await atomicWrite(repo, SPEC_PATH, text);
    await writeJson(repo, `${WORKFLOW_DIR}/owned-spec.json`, { schema_version: "wringer.workflow-owned-spec.v1", spec_sha256: digest(text) });
}
export async function answerQuestion(repo: string, id: string, text: string, actor = "operator"): Promise<NativePlan> {
    const plan = (await loadNativePlan(repo))!;
    const question = plan.questions.find(q => q.id === id);
    if (!question)
        return stop(repo, "question-unknown", `No current question has id ${id}.`, "wring plan --json");
    if (!text.trim())
        return stop(repo, "answer-empty", "An answer must contain the operator's words.", `wringer-board answer --id ${JSON.stringify(id)} --text 'YOUR ANSWER'`);
    if (question.answer === text)
        return plan;
    question.answer = text;
    await savePlan(repo, plan);
    await writeJson(repo, `${WORKFLOW_DIR}/answers/${id}-${digest(text).slice(0, 16)}.json`, { schema_version: "wringer.workflow-answer.v1", id, answer: text, actor, at: now(), source_sha256: plan.source_sha256 });
    await writeJson(repo, `${WORKFLOW_DIR}/revision-needed.json`, { status: "required", reason: "answer-changed", id, at: now() });
    return plan;
}
export async function decideAssumption(repo: string, id: string, decision: "accept" | "overrule", note = "", actor = "operator"): Promise<NativePlan> {
    const plan = (await loadNativePlan(repo))!;
    const assumption = plan.assumptions.find(a => a.id === id);
    if (!assumption)
        return stop(repo, "assumption-unknown", `No current assumption has id ${id}.`, "wring plan --json");
    if (decision === "overrule" && !note.trim())
        return stop(repo, "overrule-empty", "An overrule needs the replacement decision in the operator's own words.", `wringer-board decide --id ${JSON.stringify(id)} --overrule 'YOUR DECISION'`);
    if (assumption.human)
        return stop(repo, "human-assumption", "A delegated operator cannot turn a human requirement into an accepted assumption.", "wring plan --json");
    const status = decision === "accept" ? "accepted" : "overruled";
    if (assumption.status === status && assumption.note === note)
        return plan;
    assumption.status = status;
    assumption.note = note;
    await savePlan(repo, plan);
    await writeJson(repo, `${WORKFLOW_DIR}/decisions/${id}-${digest([status, note]).slice(0, 16)}.json`, { schema_version: "wringer.workflow-decision.v1", id, status, note, actor, at: now(), source_sha256: plan.source_sha256 });
    if (decision === "overrule")
        await writeJson(repo, `${WORKFLOW_DIR}/revision-needed.json`, { status: "required", reason: "assumption-overruled", id, at: now() });
    return plan;
}
export function renderPlan(plan: NativePlan): string {
    const rows = [`# ${plan.title}`, "", `Plan digest: ${planDigest(plan)}`, "", "## Original request", "", plan.intent, "", "## Requirements", ""];
    for (const r of plan.requirements)
        rows.push(`- ${r.id}: ${r.title} (${r.human ? "human judgement" : "machine check"}; ${r.required ? "required" : "optional"})`, `  Original words: ${JSON.stringify(r.quote)}`);
    if (plan.questions.length)
        rows.push("", "## Questions", "", ...plan.questions.map(q => `- ${q.id}: ${q.question}\n  ${q.answer ? `Recorded answer: ${q.answer}` : "UNANSWERED"}`));
    if (plan.assumptions.length)
        rows.push("", "## Decisions", "", ...plan.assumptions.map(a => `- ${a.id}: ${a.statement}\n  ${a.status}${a.note ? `: ${a.note}` : ""}`));
    rows.push("", "## Work", "", ...plan.tasks.map(t => `- ${t.id}: ${t.objective}\n  Requirements: ${t.requirement_ids.join(", ")}`), "", "## Proposed checks", "", ...plan.gates.map(g => `- ${g.id} proves ${g.proves}: ${g.run}`));
    if (Object.keys(plan.show).length)
        rows.push("", "## Human displays", "", ...Object.entries(plan.show).map(([id, run]) => `- ${id}: ${run}`));
    return rows.join("\n") + "\n";
}
async function assertReady(repo: string, plan: NativePlan) {
    const question = plan.questions.find(q => q.required && !q.answer?.trim());
    if (question)
        return stop(repo, "question-unanswered", `${question.question} (${question.id})`, `wringer-board answer --id ${JSON.stringify(question.id)} --text 'YOUR ANSWER'`);
    const assumption = plan.assumptions.find(a => a.status === "pending");
    if (assumption)
        return stop(repo, "assumption-unanswered", `${assumption.statement} (${assumption.id})`, `wringer-board decide --id ${JSON.stringify(assumption.id)} --accept`);
    const revision = await readJson<{
        status: string;
    }>(repo, `${WORKFLOW_DIR}/revision-needed.json`);
    if (revision?.status === "required")
        return stop(repo, "revision-required", "A recorded answer or overrule changed the plan. Refresh the task section before approving; earlier successful sections remain cached.", `wring spec ${JSON.stringify(`${WORKFLOW_DIR}/source.md`)} --send`);
}
export async function approveSpec(repo: string, options: {
    actor: string;
    authority?: OperatorAuthority;
    expectedDigest?: string;
}): Promise<Approval> {
    const plan = (await loadNativePlan(repo))!;
    await assertReady(repo, plan);
    const currentDigest = planDigest(plan);
    if (options.expectedDigest && options.expectedDigest !== currentDigest)
        return stop(repo, "approval-stale", "The plan changed after it was reviewed. Approval does not apply to the changed plan.", "wring plan --json");
    if (!options.actor.trim())
        return stop(repo, "approval-actor-missing", "Approval needs the identity of the operator or delegated authority.", "wringer-board approve --help");
    if (options.authority) {
        try {
            validateAuthority(options.authority, repo);
        }
        catch (error) {
            return stop(repo, "approval-not-authorized", (error as Error).message, "wringer-drive authority --help");
        }
        if (!options.authority.actions.includes("approve-plan"))
            return stop(repo, "approval-not-authorized", "This authority does not grant plan approval for this repository.", "wringer-drive authority --help");
    }
    const approval: Approval = { schema_version: "wringer.workflow-approval.v1", digest: currentDigest, actor: options.actor, at: now(), authority_sha256: options.authority ? digest(options.authority) : null };
    await writeJson(repo, `${WORKFLOW_DIR}/approval.json`, approval);
    await savePlan(repo, plan);
    return approval;
}
export async function compilePlan(repo: string): Promise<CompiledPlan> {
    const plan = (await loadNativePlan(repo))!;
    await assertReady(repo, plan);
    const spec = await loadSpec(repo);
    const approval = await readJson<Approval>(repo, `${WORKFLOW_DIR}/approval.json`);
    if (!spec.approved || !approval || approval.schema_version !== "wringer.workflow-approval.v1" || approval.digest !== planDigest(plan))
        return stop(repo, "plan-unapproved", "The exact current plan has not been approved.", `wringer-board approve --digest ${planDigest(plan)}`);
    if (stable(spec) !== stable(specFromPlan(plan, true)))
        return stop(repo, "spec-plan-disagreement", "The spec changed outside the approved native plan. The approval is invalid.", "wring plan --json");
    const sidecar = parseObject((await readText(repo, "wringer.gates.yaml")) ?? "{}", "gate proposals");
    if (stable(sidecar) !== stable(gateSidecar(plan)))
        return stop(repo, "gate-proposal-changed", "The proposed check/display commands changed after plan approval.", "wring plan --json");
    const briefPaths: string[] = [];
    const taskRows = [];
    for (const task of plan.tasks) {
        await safePath(repo, task.brief);
        const content = `<!-- Generated by @wringer/workflow; do not edit. -->\n# What you are building\n\n${plan.title}\n\n${task.objective}\n\n## Original request (verbatim)\n\n${plan.intent}\n\n## Authoritative operator decisions\n\n${plan.questions.filter(q => task.requirement_ids.some(id => q.requirement_ids.includes(id))).map(q => `${q.question}\nAnswer: ${q.answer ?? "UNANSWERED (optional)"}`).join("\n\n")}\n\n${plan.assumptions.filter(a => task.requirement_ids.some(id => a.requirement_ids.includes(id))).map(a => a.status === "overruled" ? `REPLACEMENT DECISION: ${a.note}\nSupersedes: ${a.statement}` : `Accepted: ${a.statement}`).join("\n\n")}\n\n## Requirements and proof\n\n${plan.requirements.filter(r => task.requirement_ids.includes(r.id)).map(r => `${r.id} — ${r.title}\nOriginal: ${JSON.stringify(r.quote)}\n${r.human ? `Human display: ${plan.show[r.id] ?? "absent"}` : `Check: ${plan.gates.filter(g => g.proves === r.id).map(g => `${g.id}: ${g.run}`).join("; ") || "absent"}`}`).join("\n\n")}\n\nPlan digest: ${planDigest(plan)}\nDo not modify the approval, original requirement ledger, gate declarations or evidence records. Implement the requirement; a green check alone is not evidence of satisfying it.\n`;
        const old = await readText(repo, task.brief);
        if (old !== null && !old.startsWith("<!-- Generated by @wringer/workflow; do not edit. -->"))
            return stop(repo, "brief-not-owned", `Refusing to overwrite ${task.brief}, which was not generated by this workflow.`, "wring plan --json");
        await atomicWrite(repo, task.brief, content);
        briefPaths.push(task.brief);
        taskRows.push({ id: task.id, brief: task.brief, dir: task.dir });
    }
    const tasksPath = `${WORKFLOW_DIR}/tasks.jsonl`;
    await atomicWrite(repo, tasksPath, taskRows.map(row => JSON.stringify(row)).join("\n") + "\n");
    const rubric = { schema_version: "wringer.rubric.v1", title: plan.title, criteria: spec.criteria };
    await writeJson(repo, `${WORKFLOW_DIR}/rubric.json`, rubric);
    const rubricText = JSON.stringify(rubric, null, 2) + "\n";
    const previousRubric = await readText(repo, "wringer.rubric.yaml");
    const rubricOwner = await readJson<{
        sha256: string;
    }>(repo, `${WORKFLOW_DIR}/owned-rubric.json`);
    if (previousRubric !== null && previousRubric !== rubricText && (!rubricOwner || digest(previousRubric) !== rubricOwner.sha256))
        return stop(repo, "rubric-not-owned", "wringer.rubric.yaml has an operator edit and will not be overwritten.", "wring plan --json");
    await atomicWrite(repo, "wringer.rubric.yaml", rubricText);
    await writeJson(repo, `${WORKFLOW_DIR}/owned-rubric.json`, { sha256: digest(rubricText) });
    const display = renderPlan(plan);
    await atomicWrite(repo, `${WORKFLOW_DIR}/plan.md`, display);
    return { digest: planDigest(plan), plan, spec, tasksPath, briefPaths, gates: plan.gates, show: plan.show, display };
}
