"""Prose in, testable criteria out — `wringer.spec.v1` (SPEC_INTENT_V0.md).

The front door. A product manager writes what they want in plain language;
`wring spec` drafts acceptance criteria, gates and a build plan **as a file on
disk**; a human reads and approves that file; `wring plan` compiles it into
work a fleet can run.

The failure mode this module exists to prevent is not a bad build — it is a
*confident build of the wrong thing*. Three defences, all structural, all
here rather than in the prompt:

1. **`approved` is never read from the model.** `draft()` writes
   `approved: false` unconditionally; there is no code path along which a
   reply, a flag or an environment variable can set it true. A human edits the
   file, which is why there is no `--yes`.
2. **`intent` is written from the PRD, not from the reply.** A model
   paraphrasing the human's own words inside the artifact the human is about
   to approve is the confident-wrong-answer in miniature, so Wringer quotes
   the source file and ignores whatever the model called it.
3. **Everything proposed is validated by the real parser.** Criteria go
   through `rubric.parse_document`, gates through `config.parse_gate`. Wringer
   cannot propose a rubric the judge would reject or a gate `.wringer.yaml`
   would refuse, because the same code decides both.

**This module opens no socket.** `wring spec --send` reuses `judge.send` — the
one function in Wringer that does — with the `judge:` section's endpoint,
model and key rules verbatim. One network config, one set of safety rules, one
auditable path (SPEC_INTENT_V0.md §2).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from wringer import config, evidence
from wringer.redact import Redactor
from wringer.rubric import (
    MAX_RUBRIC_BYTES,
    Criterion,
    RubricError,
    parse_document,
)

SCHEMA_VERSION = "wringer.spec.v1"
SPEC_FILENAME = "wringer.spec.yaml"
RUBRIC_FILENAME = "wringer.rubric.yaml"

# The gate sidecar (SPEC_GATEGEN_V0). A SEPARATE FILE because
# `wringer.spec.v1` is frozen and its `gates:` entries have no `proves`
# channel — law 7 says a new format is a new file, never an edit to a
# published one.
#
# **This file has no authority whatsoever.** Nothing under `.wringer/` is
# written from it, no gate in it ever runs, and `verify`, `run`, `fleet`,
# `graph` and `deliver` never open it. It is a proposal that becomes real
# only when a person applies `wring plan`'s diff to `.wringer.yaml`, which
# stays the one file that puts a command in Wringer's mouth (SPEC_GRAPH
# ruling 1).
GATESPEC_FILENAME = "wringer.gates.yaml"
GATESPEC_SCHEMA_VERSION = "wringer.gatespec.v1"
_GATESPEC_KEYS = {"schema_version", "gates"}
TASKS_FILENAME = "tasks.jsonl"
SPECS_DIRNAME = Path(".wringer") / "specs"
REQUEST_FILENAME = "request.json"
RESPONSE_FILENAME = "response.json"
SUMMARY_FILENAME = "summary.md"

# A PRD is a page or two. These bytes travel to an endpoint, so they get the
# rubric's treatment: a declared ceiling rather than whatever the disk holds.
MAX_PRD_BYTES = 64 * 1024
# How much of the PRD is quoted verbatim into `intent`. The whole thing when
# it fits, which for a real PRD it does.
MAX_INTENT_CHARS = 8000
MAX_SPEC_BYTES = 128 * 1024
# A PRD that yields fifty tasks was not understood. The fleet can run hundreds;
# a single drafting pass proposing them is a sign to read the reply, not to
# start it.
MAX_TASKS = 50
MAX_OPEN_QUESTIONS = 20

# Every brief `wring plan` writes starts with this line, and `wring plan`
# refuses to overwrite a file that does not carry it. Briefs are generated
# from the spec on every run; a hand-written file that happened to share a
# name must not be silently replaced.
BRIEF_MARKER = (
    "<!-- generated by `wring plan` from wringer.spec.yaml — "
    "edits here are overwritten; edit the spec -->"
)
# The same guard for the rubric, which a repo may well have written by hand
# and committed long before it ever ran `wring spec` — `judge.rubric:` has
# pointed at a file since v0.2. A YAML comment, so `rubric.load` is unmoved.
RUBRIC_MARKER = (
    "# generated by `wring plan` from wringer.spec.yaml — "
    "edits here are overwritten; edit the spec"
)
# The same guard for the sidecar, and it earns it twice over: an offline repo
# writes this file BY HAND (ruling 5), so `wring spec --send` must never
# silently replace a person's own gate proposals with a model's.
GATESPEC_MARKER = (
    "# proposed by `wring spec` from the drafted criteria — a PROPOSAL with "
    "no authority until you apply `wring plan`'s diff to .wringer.yaml"
)

_TOP_LEVEL_KEYS = {
    "schema_version",
    "approved",
    "title",
    "intent",
    "open_questions",
    "criteria",
    "gates",
    "tasks",
}
_QUESTION_KEYS = {"id", "question", "required", "answer"}
_TASK_KEYS = {"id", "brief", "dir", "objective"}


class SpecError(Exception):
    """An unusable spec, PRD or reply (CLI exit code 2)."""


@dataclass(frozen=True)
class Question:
    id: str
    question: str
    required: bool = True
    answer: str = ""

    @property
    def answered(self) -> bool:
        """A question is answered when someone wrote an answer under it.

        Deleting the question works too — it is simply gone. Both are file
        edits, which is the only kind of approval this slice accepts.
        """
        return bool(self.answer.strip())


@dataclass(frozen=True)
class Task:
    id: str
    brief: str
    objective: str
    dir: str = "."


@dataclass(frozen=True)
class Draft:
    """What one drafting reply yielded: the spec, and the gates it proposed.

    Two documents rather than one field on `Spec`, because `Spec` maps to a
    frozen schema and a proposed binding has no home in it. Returned together
    so a caller cannot write the spec and forget the sidecar, or write a
    sidecar whose bindings were never checked against the criteria beside it.
    """

    spec: Spec
    gates: tuple[config.Gate, ...] = ()


@dataclass(frozen=True)
class Spec:
    approved: bool
    title: str
    intent: str
    questions: tuple[Question, ...]
    criteria: tuple[Criterion, ...]
    gates: tuple[config.Gate, ...]
    tasks: tuple[Task, ...]
    path: str

    @property
    def unanswered(self) -> tuple[Question, ...]:
        return tuple(q for q in self.questions if q.required and not q.answered)


# --- reading a spec file -------------------------------------------------


def authorising_sha256(root: Path) -> str | None:
    """The hash of the spec that authorised this work, if there is one.

    `wringer.spec.yaml` is the document a human approved — the `approved:
    true` in it is the authority everything downstream runs on. Nothing
    recorded *which* spec that was, so `wring attest`'s first clause
    ("authorized by spec S") had nothing to point at, and a spec could be
    edited after approval with no trace.

    Cheap here, impossible later: this goes into manifests whose schemas stop
    being amendable when 0.2.0 tags.
    """
    import hashlib

    path = root / SPEC_FILENAME
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return None


def load(path: Path) -> Spec:
    """Read and validate `wringer.spec.yaml`.

    Re-read from disk on every `wring plan`, never cached and never carried
    over from the drafting run: `approved` means what the file says now.
    """
    if not path.is_file():
        raise SpecError(
            f"no {path.name} in {path.parent} — draft one with "
            f"'wring spec <PRD.md>'"
        )
    raw_bytes = path.read_bytes()
    if len(raw_bytes) > MAX_SPEC_BYTES:
        raise SpecError(
            f"{path.name} is {len(raw_bytes)} bytes, over the "
            f"{MAX_SPEC_BYTES}-byte limit"
        )
    try:
        data = yaml.safe_load(raw_bytes.decode("utf-8"))
    except (yaml.YAMLError, UnicodeDecodeError) as exc:
        raise SpecError(f"{path.name} is not valid YAML: {exc}") from exc
    return parse(data, path.name)


def parse(data: Any, where: str) -> Spec:
    """Validate a spec mapping — strict, like every other loader here."""
    if not isinstance(data, dict):
        raise SpecError(f"{where}: top level must be a mapping")

    unknown = sorted(set(data) - _TOP_LEVEL_KEYS)
    if unknown:
        raise SpecError(f"{where}: unknown keys: {', '.join(unknown)}")

    declared = data.get("schema_version")
    if declared != SCHEMA_VERSION:
        raise SpecError(
            f"{where}: 'schema_version: {SCHEMA_VERSION}' is required "
            f"(got {declared!r})"
        )

    approved = data.get("approved")
    if not isinstance(approved, bool):
        raise SpecError(
            f"{where}: 'approved' must be a boolean, and must be present — it "
            "is the interlock, so a spec that forgot to say is not approved by "
            "omission"
        )

    title = _nonempty(data.get("title"), f"{where}: 'title'")
    intent = _nonempty(data.get("intent"), f"{where}: 'intent'")

    questions = _parse_questions(data.get("open_questions"), where)

    criteria_raw = data.get("criteria")
    try:
        _, criteria = parse_document(
            {
                "schema_version": "wringer.rubric.v1",
                "title": title,
                "criteria": criteria_raw,
            },
            where,
        )
    except RubricError as exc:
        raise SpecError(str(exc)) from exc

    gates_raw = data.get("gates") or []
    if not isinstance(gates_raw, list):
        raise SpecError(f"{where}: 'gates' must be a list")
    try:
        gates = tuple(
            config.parse_gate(entry, index, where)
            for index, entry in enumerate(gates_raw)
        )
    except config.ConfigError as exc:
        raise SpecError(str(exc)) from exc
    seen: set[str] = set()
    for gate in gates:
        if gate.id in seen:
            raise SpecError(f"{where}: duplicate gate id '{gate.id}'")
        seen.add(gate.id)

    tasks = _parse_tasks(data.get("tasks"), where)

    return Spec(
        approved=approved,
        title=title,
        intent=intent,
        questions=questions,
        criteria=criteria,
        gates=gates,
        tasks=tasks,
        path=where,
    )


def _nonempty(value: Any, at: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise SpecError(f"{at} must be a non-empty string")
    return value


def _slug(value: Any, at: str) -> str:
    identifier = _nonempty(value, at)
    if len(identifier) > config.MAX_GATE_ID_LENGTH or not (
        config.GATE_ID_PATTERN.fullmatch(identifier)
    ):
        raise SpecError(
            f"{at} ('{identifier}') must be a slug — letters, digits, '-' and "
            "'_', starting with a letter or digit"
        )
    return identifier


def _parse_questions(raw: Any, where: str) -> tuple[Question, ...]:
    if raw is None:
        return ()
    if not isinstance(raw, list):
        raise SpecError(f"{where}: 'open_questions' must be a list")
    if len(raw) > MAX_OPEN_QUESTIONS:
        raise SpecError(
            f"{where}: {len(raw)} open questions, over the limit of "
            f"{MAX_OPEN_QUESTIONS} — a spec that unclear needs a conversation, "
            "not a form"
        )

    questions: list[Question] = []
    seen: set[str] = set()
    for index, entry in enumerate(raw):
        at = f"{where}: open_questions[{index}]"
        if not isinstance(entry, dict):
            raise SpecError(f"{at} must be a mapping")
        unknown = sorted(set(entry) - _QUESTION_KEYS)
        if unknown:
            raise SpecError(f"{at}: unknown keys: {', '.join(unknown)}")

        question_id = _slug(entry.get("id"), f"{at}: 'id'")
        if question_id in seen:
            raise SpecError(f"{at}: duplicate question id '{question_id}'")
        seen.add(question_id)

        required = entry.get("required", True)
        if not isinstance(required, bool):
            raise SpecError(f"{at} ('{question_id}'): 'required' must be a boolean")
        answer = entry.get("answer", "")
        if answer is None:
            answer = ""
        if not isinstance(answer, str):
            raise SpecError(f"{at} ('{question_id}'): 'answer' must be a string")

        questions.append(
            Question(
                id=question_id,
                question=_nonempty(entry.get("question"), f"{at}: 'question'"),
                required=required,
                answer=answer,
            )
        )
    return tuple(questions)


def _parse_tasks(raw: Any, where: str) -> tuple[Task, ...]:
    if not isinstance(raw, list) or not raw:
        raise SpecError(f"{where}: 'tasks' must be a non-empty list")
    if len(raw) > MAX_TASKS:
        raise SpecError(
            f"{where}: {len(raw)} tasks, over the limit of {MAX_TASKS} — a "
            "single drafting pass proposing that many was not understanding "
            "the PRD"
        )

    tasks: list[Task] = []
    seen: set[str] = set()
    for index, entry in enumerate(raw):
        at = f"{where}: tasks[{index}]"
        if not isinstance(entry, dict):
            raise SpecError(f"{at} must be a mapping")
        unknown = sorted(set(entry) - _TASK_KEYS)
        if unknown:
            raise SpecError(f"{at}: unknown keys: {', '.join(unknown)}")

        # The same slug rule as a fleet task id, because this becomes one.
        task_id = _slug(entry.get("id"), f"{at}: 'id'")
        if task_id in seen:
            raise SpecError(f"{at}: duplicate task id '{task_id}'")
        seen.add(task_id)

        brief = _nonempty(entry.get("brief"), f"{at} ('{task_id}'): 'brief'")
        _check_contained(brief, f"{at} ('{task_id}'): 'brief'")
        directory = entry.get("dir", ".")
        if not isinstance(directory, str) or not directory.strip():
            raise SpecError(f"{at} ('{task_id}'): 'dir' must be a non-empty string")
        _check_contained(directory, f"{at} ('{task_id}'): 'dir'")

        tasks.append(
            Task(
                id=task_id,
                brief=brief,
                objective=_nonempty(
                    entry.get("objective"), f"{at} ('{task_id}'): 'objective'"
                ),
                dir=directory,
            )
        )
    return tuple(tasks)


def _check_contained(candidate: str, at: str) -> None:
    """Refuse any path that could leave the repository.

    `wring plan` **writes** brief files at these paths, and the paths were
    proposed by a model. An absolute path or a `..` here is the difference
    between generating a document and overwriting `~/.ssh/config`. Checked on
    the string, before any filesystem call, so a symlink cannot answer for it.
    """
    # Before any Path() call: a NUL reaches the OS layer and raises ValueError
    # out of stat(), which is a crash where a refusal belongs.
    if any(ch == "\x00" or (ch < " " and ch not in "\t") for ch in candidate):
        raise SpecError(f"{at} contains a control character")
    path = Path(candidate)
    if path.is_absolute() or candidate.startswith("~"):
        raise SpecError(f"{at} must be a path relative to the repository root")
    if ".." in path.parts:
        raise SpecError(f"{at} must not escape the repository with '..'")


def resolve_inside(root: Path, candidate: str, at: str) -> Path:
    """The absolute path for a spec-declared relative path, or refuse it.

    Belt and braces over `_check_contained`: that one reads the string, this
    one resolves it and checks the answer is still under `root`, which is what
    catches a symlinked directory pointing out of the tree.
    """
    _check_contained(candidate, at)
    resolved = (root / candidate).resolve()
    if not resolved.is_relative_to(root.resolve()):
        raise SpecError(f"{at} resolves outside the repository ({resolved})")
    return resolved


# Files `wring plan` writes itself, or that describe the work. A spec-declared
# brief pointing at one of these would destroy the artifact plan just produced
# — and plan would then report having written it.
RESERVED_WRITE_PATHS = (
    SPEC_FILENAME,
    TASKS_FILENAME,
    RUBRIC_FILENAME,
    config.CONFIG_FILENAME,
)


def check_writable(root: Path, candidate: str, at: str) -> Path:
    """Resolve a path `wring plan` is about to WRITE, or refuse it.

    Everything `resolve_inside` refuses, plus the hazards that only matter
    because this end of the path is a write and a model chose it.
    """
    resolved = resolve_inside(root, candidate, at)
    relative = resolved.relative_to(root.resolve())

    if relative.parts and relative.parts[0] == ".git":
        raise SpecError(
            f"{at} points inside .git/ — Wringer never writes git state, and a "
            "brief that did would corrupt the repository rather than describe "
            "a task"
        )
    if relative.as_posix() in RESERVED_WRITE_PATHS:
        raise SpecError(
            f"{at} names {relative.as_posix()}, which `wring plan` writes or "
            "reads itself — writing a brief over it would destroy the plan and "
            "then report success"
        )
    if resolved.is_dir():
        raise SpecError(f"{at} names an existing directory")
    # A parent that exists and is not a directory makes mkdir raise *after*
    # earlier files are already on disk — the half-ran state the caller
    # promises is impossible. Catch it while nothing has been written.
    for parent in relative.parents:
        candidate_parent = root / parent
        if candidate_parent.exists() and not candidate_parent.is_dir():
            raise SpecError(
                f"{at}: '{parent.as_posix()}' exists and is not a directory"
            )
    return resolved


# --- drafting ------------------------------------------------------------


def read_prd(path: Path, root: Path, redactor: Redactor | None = None) -> str:
    """The PRD's text, bounded, confined to the repo, and scrubbed.

    Its bytes travel to an endpoint, so it gets the rubric's rules: inside the
    repository, under a declared ceiling.

    **Scrubbed here, at the read**, not on the way to disk. Scrubbing only the
    artifact would produce a `request.json` saying `[REDACTED]` beside a socket
    that carried the real value — an audit record that denies what actually
    left the machine, which is worse than no audit record at all. Everything
    downstream (the request, the quoted `intent`, the briefs) is built from
    this one scrubbed string, so all of them agree.
    """
    try:
        resolved = path.resolve()
        inside = resolved.is_relative_to(root.resolve())
    except OSError as exc:  # pragma: no cover - unreadable path
        raise SpecError(f"cannot read {path}: {exc}") from exc
    if not inside:
        raise SpecError(
            f"PRD {path} resolves outside the repository ({resolved}) — its "
            "contents would be sent to an endpoint, so it must be a file the "
            "repo itself holds"
        )
    if not resolved.is_file():
        raise SpecError(f"no PRD at {path}")

    raw = resolved.read_bytes()
    if len(raw) > MAX_PRD_BYTES:
        raise SpecError(
            f"PRD {path} is {len(raw)} bytes, over the {MAX_PRD_BYTES}-byte "
            "limit — these bytes travel"
        )
    text = raw.decode("utf-8", errors="replace").strip()
    if not text:
        raise SpecError(f"PRD {path} is empty — there is nothing to draft from")
    return (redactor or Redactor()).scrub(text)


def quote_intent(prd: str) -> str:
    """The human's own words, verbatim, for the artifact they will approve.

    Never the model's summary of them. If a drafter misread the PRD, the
    reader needs the PRD beside the criteria to notice.
    """
    # Control characters YAML cannot carry in a block scalar. A PRD holding
    # one would otherwise produce a spec file that will not load — and the
    # first thing anyone would do with it is approve it.
    quoted = "".join(
        ch for ch in prd if ch in "\t\n" or (ch >= " " and ch != "\x7f")
    )
    if len(quoted) <= MAX_INTENT_CHARS:
        return quoted
    return (
        quoted[:MAX_INTENT_CHARS]
        + f"\n\n[wringer: quoted the first {MAX_INTENT_CHARS} characters of "
        "the PRD; read the file itself for the rest]"
    )


def render_request(
    prd: str,
    model: str,
    max_output_tokens: int,
    declared: tuple[config.Gate, ...] = (),
) -> dict:
    """The exact chat-completions body.

    Built from the PRD and, if the repo has any, the gate commands it already
    declares — shown so the drafter can propose *those* rather than guess at a
    build system it cannot see. A drafter shown nothing invents; law 5 is why
    the proposals are a diff a human applies, and this is how to need that
    safety net less often.
    """
    known = "\n".join(f"- {g.id}: {g.run}" for g in declared)
    user = (
        "# Product requirements\n\n"
        f"{prd}\n\n"
        "---\n\n"
        + (
            f"## Gates this repository already declares\n{known}\n\n"
            "Propose only gates that are missing, and phrase them the way "
            "these are.\n\n"
            if known
            else ""
        )
        + "## Your task\n"
        "Turn the requirements above into a build specification.\n\n"
        "Rules, in order of importance:\n"
        "1. **Never guess.** Anything you had to assume becomes an entry in "
        "`open_questions` instead. A question is better than a wrong "
        "criterion.\n"
        "2. **Every criterion must be checkable.** Prefer criteria a test or "
        "a lint can decide. Mark a criterion `\"human\": true` when only a "
        "person can judge it — taste, tone, or a trade-off.\n"
        "3. **Propose gates the repository could actually run** — its own "
        "test and lint commands. Propose none rather than inventing one.\n"
        "4. Split the work into tasks a single agent can finish. Give each an "
        "`objective`: one paragraph saying what done looks like.\n"
        "5. **For each criterion a machine can decide, propose a "
        "`gate_bindings` entry**: a command that FAILS today and passes only "
        "once that criterion is met, and the criterion id it proves. One "
        "criterion, one binding, and never a `human: true` one. **A binding "
        "that already passes is worth nothing** — the criterion is unbuilt, "
        "so a command that is green now is not testing it. Omit any binding "
        "you cannot write that way rather than writing a weak one.\n"
        "6. **A binding must run a check that EXISTS TODAY.** Every file it "
        "names must already be in the repository. Do not name a test file "
        "that would have to be written — it would fail because it is absent "
        "rather than because the criterion is unmet, and a check that arrives "
        "with the work cannot evidence the work. If no existing check can "
        "decide a criterion, propose no binding for it and say so in "
        "`open_questions`.\n\n"
        "## Reply format\n"
        "Return ONLY a JSON object, no prose and no code fence:\n"
        "{\n"
        '  "title": "<one line>",\n'
        '  "open_questions": [{"id": "<slug>", "question": "<one line>", '
        '"required": true}],\n'
        '  "criteria": [{"id": "<slug>", "title": "<one line>", '
        '"guidance": "<how to check it>", "required": true, "human": false}],\n'
        '  "gates": [{"id": "<slug>", "run": "<shell command>"}],\n'
        '  "gate_bindings": [{"id": "<slug>", "run": "<shell command>", '
        '"proves": "<criterion id from above>"}],\n'
        '  "tasks": [{"id": "<slug>", "brief": "briefs/<slug>.md", '
        '"dir": ".", "objective": "<one paragraph>"}]\n'
        "}\n"
        "Slugs are letters, digits, '-' and '_'. At least one criterion must "
        "be `required`. At least one task. `gates` are the repository's "
        "existing checks; `gate_bindings` are the per-criterion acceptance "
        "checks, and only these carry `proves`."
    )
    # **No `temperature` key, and its absence is the fix rather than an
    # omission.** Until 2026-08-18 this body carried `"temperature": 0`, and
    # every current-generation Anthropic model — Opus 5, Opus 4.8, Opus 4.7,
    # Sonnet 5, Fable 5 — refuses it outright: HTTP 400, *"`temperature` is
    # deprecated for this model"*, before a token is drafted. So a product
    # manager who named the model their team actually uses got an error
    # instead of a spec, which is the whole surface failing at its first step.
    #
    # No config knob replaces it, deliberately. `temperature: 0` never bought
    # determinism here — the drafter's correctness mechanism is
    # parse-or-refuse (`parse_response` puts every proposed field through the
    # same parser the file itself will face), not sampling temperature. A
    # `judge.temperature` key would be surface nobody asked for, and if a real
    # need arrives it can arrive with a use case.
    #
    # `wring judge` is a DIFFERENT request and keeps its `temperature: 0`:
    # `schema/judge-request.schema.json` requires it with `"const": 0`, that
    # schema is frozen (`schema/frozen.json`), and a judge that is not
    # deterministic is not a gate. Nothing here changes it.
    #
    # Old `request.json` files keep their `temperature` and stay readable:
    # nothing reads the key back out, and no schema governs this body.
    return {
        "model": model,
        "max_tokens": max_output_tokens,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You turn product requirements into a build specification: "
                    "acceptance criteria, gates, and tasks. You never invent a "
                    "requirement — anything the document does not say becomes "
                    "an open question. Answer only with the requested JSON."
                ),
            },
            {"role": "user", "content": user},
        ],
    }


def parse_response(body: Any, prd: str) -> Draft:
    """Turn a model reply into a validated spec and its proposed gates, or
    refuse the whole reply.

    Every field the model proposes goes through the same parser the file
    itself will face, so the caller either gets a spec that loads or an
    exception — never a half-formed document to write out and apologise for.

    `approved` is not read from the reply. There is no key here that could
    set it.
    """
    try:
        content = body["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError):
        raise SpecError(
            "the reply had no message content — nothing was drafted, and "
            "nothing was written"
        ) from None
    try:
        drafted = json.loads(_strip_fences(str(content)))
    except (ValueError, json.JSONDecodeError) as exc:
        raise SpecError(
            f"the reply was not the JSON object the request asked for ({exc}) "
            "— nothing was written"
        ) from exc
    if not isinstance(drafted, dict):
        raise SpecError("the reply was JSON but not an object — nothing was written")

    # Strict, like every other loader here, and loudest where it matters: a
    # reply carrying `approved` is a reply that tried to work the interlock,
    # and the honest answer to that is a refusal a human reads, not a silent
    # discard.
    unknown = sorted(
        set(drafted)
        - {"title", "open_questions", "criteria", "gates", "tasks",
           "gate_bindings"}
    )
    if unknown:
        raise SpecError(
            f"the reply carried keys the request did not ask for: "
            f"{', '.join(unknown)} — nothing was written"
        )

    asked = drafted.get("open_questions") or []
    if isinstance(asked, list):
        answered = [
            q.get("id") for q in asked
            if isinstance(q, dict) and str(q.get("answer") or "").strip()
        ]
        if answered:
            # The second interlock, and the reply tried to work it. An
            # `answer` written by the drafter is the assumption it was told to
            # ask about, wearing a human's clothes: `wring plan` would let it
            # through and the brief would present it as a decision someone
            # made. Refused for the same reason as `approved`.
            raise SpecError(
                "the reply answered its own open question"
                f"{'s' if len(answered) > 1 else ''} "
                f"({', '.join(str(q) for q in answered)}) — an assumption a "
                "human did not make is exactly what an open question is for. "
                "Nothing was written"
            )

    drafted_spec = parse(
        {
            "schema_version": SCHEMA_VERSION,
            # Written here, not read from the reply. The interlock is a
            # constant in this expression; there is no branch that sets it.
            "approved": False,
            "title": drafted.get("title"),
            # The human's words, not the model's paraphrase of them.
            "intent": quote_intent(prd),
            "open_questions": drafted.get("open_questions") or [],
            "criteria": drafted.get("criteria"),
            "gates": drafted.get("gates") or [],
            "tasks": drafted.get("tasks"),
        },
        "the drafted spec",
    )
    # Checked at draft time, not left for `wring plan`: a spec that reads fine,
    # gets approved, and only then turns out to be unplannable spends the
    # human's attention for nothing.
    validate_rubric_text(render_rubric(drafted_spec))
    # Checked here, before the caller writes anything, and against the
    # criteria from THIS reply: a sidecar validated later would mean a spec on
    # disk whose companion file was refused, and the pair only means anything
    # together.
    proposed = parse_bindings(
        drafted.get("gate_bindings"), drafted_spec.criteria, "the drafted gates"
    )
    return Draft(spec=drafted_spec, gates=proposed)


def parse_bindings(raw: Any, criteria: Any, where: str) -> tuple[config.Gate, ...]:
    """The proposed gates, or a refusal — checked against the criteria beside
    them before a byte of either document is written.

    Every entry goes through `config.parse_gate` with `allow_proves=True`:
    the SAME parser `.wringer.yaml` will face, so Wringer can never propose a
    gate its own loader would reject — the rule the spec's `gates:` block has
    had since P2, extended to the channel that carries bindings.

    The join is then `config.check_bindings`, the shipped rules, not a copy.
    """
    if raw is None:
        return ()
    if not isinstance(raw, list):
        raise SpecError(f"{where}: 'gate_bindings' must be a list")

    gates: list[config.Gate] = []
    for index, entry in enumerate(raw):
        try:
            gate = config.parse_gate(entry, index, where, allow_proves=True)
        except config.ConfigError as exc:
            raise SpecError(str(exc)) from exc
        if not gate.proves:
            raise SpecError(
                f"{where}: gate_bindings[{index}] ('{gate.id}') names no "
                "'proves'. This file is the binding channel and nothing else; "
                "a gate that evidences no criterion belongs in the spec's own "
                "'gates:' block, where it already goes"
            )
        gates.append(gate)

    try:
        config.check_bindings(gates, {c.id: c for c in criteria}, where)
    except config.ConfigError as exc:
        raise SpecError(str(exc)) from exc
    return tuple(gates)


def parse_gatespec(data: Any, where: str, criteria: Any) -> tuple[config.Gate, ...]:
    """Read `wringer.gates.yaml` — hand-written or drafted, same parser."""
    if not isinstance(data, dict):
        raise SpecError(f"{where}: top level must be a mapping")
    unknown = sorted(set(data) - _GATESPEC_KEYS)
    if unknown:
        raise SpecError(f"{where}: unknown keys: {', '.join(unknown)}")
    declared = data.get("schema_version")
    if declared != GATESPEC_SCHEMA_VERSION:
        raise SpecError(
            f"{where}: 'schema_version: {GATESPEC_SCHEMA_VERSION}' is "
            f"required (got {declared!r})"
        )
    return parse_bindings(data.get("gates"), criteria, where)


def load_gatespec(root: Path, criteria: Any) -> tuple[config.Gate, ...]:
    """The sidecar's proposals, or none because there is no sidecar.

    Absent is not an error: the file is optional everywhere, and a repo that
    binds its criteria by hand never grows one.
    """
    path = root / GATESPEC_FILENAME
    if not path.is_file():
        return ()
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError, UnicodeDecodeError) as exc:
        raise SpecError(f"{GATESPEC_FILENAME} is not valid YAML: {exc}") from exc
    return parse_gatespec(data, GATESPEC_FILENAME, criteria)


def render_gatespec(gates: Any) -> str:
    """The sidecar as the file a human reads, edits, or writes from scratch."""
    lines = [
        GATESPEC_MARKER,
        f"schema_version: {GATESPEC_SCHEMA_VERSION}",
        "",
        "gates:",
    ]
    for gate in gates:
        lines += [f"  - id: {gate.id}", f"    run: {_scalar(gate.run)}"]
        if gate.timeout != config.DEFAULT_TIMEOUT_SECONDS:
            lines.append(f"    timeout: {gate.timeout}")
        lines.append(f"    proves: {gate.proves}")
    return "\n".join(lines) + "\n"


def gatespec_is_generated(path: Path) -> bool:
    return _carries(path, GATESPEC_MARKER)


def _strip_fences(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        lines = lines[1:-1] if len(lines) > 2 and lines[-1].startswith("```") \
            else lines[1:]
        return "\n".join(lines)
    return stripped


def render(spec: Spec) -> str:
    """The spec as the file a human reads and edits.

    Hand-rolled rather than `yaml.dump` because this document is a form: the
    interlock needs a comment beside it, and the questions need room to be
    answered in. A dumped mapping would be correct and unreadable.
    """
    lines = [
        f"# {SCHEMA_VERSION} — drafted by `wring spec`, approved by you.",
        "#",
        "# Nothing runs until 'approved' below says true, and only a person",
        "# can make it say that: there is no flag, and no --yes.",
        "",
        f"schema_version: {SCHEMA_VERSION}",
        f"approved: {str(spec.approved).lower()}"
        "        # <- the interlock. `wring plan` refuses while this is false.",
        f"title: {_scalar(spec.title)}",
        "",
        "# Your own words, quoted from the PRD. Check the criteria below",
        "# against this, not against what you meant to write.",
        # An explicit indentation indicator, because a PRD whose first line is
        # itself indented would otherwise set the block's indent for every
        # line after it and silently reflow the quote.
        "intent: |2",
    ]
    lines += [f"  {line}".rstrip() for line in spec.intent.splitlines()]

    lines += ["", "# Answer each question by writing an 'answer:' line under it,"]
    lines += ["# or delete the question. `wring plan` refuses while a required"]
    lines += ["# one is unanswered.", "open_questions:"]
    if not spec.questions:
        lines[-1] = "open_questions: []"
    for question in spec.questions:
        lines += [
            f"  - id: {question.id}",
            f"    question: {_scalar(question.question)}",
            f"    required: {str(question.required).lower()}",
            f"    answer: {_scalar(question.answer)}",
        ]

    lines += [
        "",
        "# The acceptance criteria — a wringer.rubric.v1 document, which is",
        "# what `wring judge` will weigh the finished change against.",
        "# 'human: true' means no judge may score it; a person must.",
        "criteria:",
    ]
    for criterion in spec.criteria:
        lines += [
            f"  - id: {criterion.id}",
            f"    title: {_scalar(criterion.title)}",
        ]
        if criterion.guidance:
            lines.append(f"    guidance: {_scalar(criterion.guidance)}")
        lines += [
            f"    required: {str(criterion.required).lower()}",
            f"    human: {str(criterion.human).lower()}",
        ]

    lines += [
        "",
        "# Proposed gates. `wring plan` prints these as a diff against",
        "# .wringer.yaml and stops — Wringer never installs a gate itself.",
        "gates:" if spec.gates else "gates: []",
    ]
    for gate in spec.gates:
        lines += [f"  - id: {gate.id}", f"    run: {_scalar(gate.run)}"]
        if gate.timeout != config.DEFAULT_TIMEOUT_SECONDS:
            lines.append(f"    timeout: {gate.timeout}")
        if gate.optional:
            lines.append("    optional: true")

    lines += [
        "",
        "# The build plan. `wring plan` turns these into tasks.jsonl and",
        "# writes each brief to the path named here.",
        "tasks:",
    ]
    for task in spec.tasks:
        lines += [
            f"  - id: {task.id}",
            f"    brief: {_scalar(task.brief)}",
            f"    dir: {_scalar(task.dir)}",
            f"    objective: {_scalar(task.objective)}",
        ]
    return "\n".join(lines) + "\n"


def _scalar(value: str) -> str:
    """One YAML scalar, on exactly one line, holding exactly `value`.

    A JSON string is a YAML double-quoted scalar, so `json.dumps` is the
    emitter: it quotes unconditionally, escapes every C0 control character,
    and — the property this needs — can never emit a line break. This renderer
    builds the file line by line, and a scalar that decided to span three of
    them would land at an indentation nobody chose.

    The two escapes JSON does not make are added by hand: U+2028 and U+2029
    are ordinary characters to JSON and **line breaks to YAML**. `\\x85` is
    the same story.

    Nothing is stripped. An earlier version trimmed the emitter's trailing
    document marker with `.strip()`, which also ate any leading or trailing
    Unicode whitespace in the value itself — so a title ending in a non-
    breaking space was quietly written down as a different title.
    """
    dumped = json.dumps(value, ensure_ascii=False)
    for char in ("\x85", " ", " "):
        dumped = dumped.replace(char, f"\\u{ord(char):04x}")

    # The file is meant to be read, and quoting every scalar is noise. So try
    # the plain form — and *check* it, rather than assuming which cases are
    # safe. If it does not read back byte-identical on one line, the quoted
    # form stands. A prettifier that guesses is how the last bug got in.
    plain = (
        yaml.safe_dump(value, default_flow_style=True, allow_unicode=True,
                       width=10**6)
        .removesuffix("\n...\n")
        .removesuffix("\n")
    )
    if plain and "\n" not in plain:
        try:
            if yaml.safe_load(f"k: {plain}")["k"] == value:
                return plain
        except (yaml.YAMLError, KeyError, TypeError):
            pass
    return dumped


# --- planning ------------------------------------------------------------


def render_rubric(spec: Spec) -> str:
    """The criteria block as a standalone `wringer.rubric.v1` file.

    No translation layer: the same criteria, the same keys, the same parser.
    """
    document: dict[str, Any] = {
        "schema_version": "wringer.rubric.v1",
        "title": spec.title,
        "criteria": [
            {
                "id": c.id,
                "title": c.title,
                **({"guidance": c.guidance} if c.guidance else {}),
                "required": c.required,
                "human": c.human,
            }
            for c in spec.criteria
        ],
    }
    return RUBRIC_MARKER + "\n" + yaml.safe_dump(
        document, sort_keys=False, allow_unicode=True
    )


def validate_rubric_text(text: str) -> None:
    """Prove a rendered rubric is one, before it is written.

    Runs the judge's own parser and the judge's own size limit. If this passes,
    `rubric.load` on the written file cannot fail — which is what "the criteria
    block is a rubric by construction" has to mean to be worth saying.
    """
    encoded = len(text.encode("utf-8"))
    if encoded > MAX_RUBRIC_BYTES:
        raise SpecError(
            f"the criteria render to {encoded} bytes, over the "
            f"{MAX_RUBRIC_BYTES}-byte rubric limit — these bytes travel"
        )
    try:
        parse_document(yaml.safe_load(text), RUBRIC_FILENAME)
    except (RubricError, yaml.YAMLError) as exc:
        raise SpecError(f"the criteria are not a usable rubric: {exc}") from exc


def render_brief(spec: Spec, task: Task) -> str:
    """One task's brief — a file, never an inline payload (invariant 5)."""
    lines = [
        BRIEF_MARKER,
        "",
        f"# {task.id} — {spec.title}",
        "",
        "## Objective",
        "",
        task.objective,
        "",
        "## Acceptance criteria",
        "",
        "These are what the change will be judged against.",
        "",
    ]
    for criterion in spec.criteria:
        tags = []
        if not criterion.required:
            tags.append("optional")
        if criterion.human:
            tags.append("a human scores this")
        suffix = f" _({', '.join(tags)})_" if tags else ""
        lines.append(f"- **{criterion.id}** — {criterion.title}{suffix}")
        if criterion.guidance:
            lines.append(f"  - {criterion.guidance}")

    answered = [q for q in spec.questions if q.answered]
    if answered:
        lines += ["", "## Decisions already made", ""]
        lines += [f"- **{q.question}** {q.answer}" for q in answered]

    lines += [
        "",
        "## What the product manager asked for",
        "",
        "```",
        spec.intent,
        "```",
        "",
    ]
    return "\n".join(lines)


def render_tasks(spec: Spec) -> str:
    """`tasks.jsonl`, exactly the shape `fleet.load_tasks` accepts."""
    return "".join(
        json.dumps({"id": t.id, "brief": t.brief, "dir": t.dir}) + "\n"
        for t in spec.tasks
    )


def declared_gate_ids(existing: str) -> set[str]:
    """The gate ids a config already has.

    Parsed properly when the file parses, because a missed id means proposing
    a duplicate — and a human who applied that diff would be left with a
    config their own loader rejects. The line scan is only the fallback for a
    file that does not parse at all, which still deserves a diff.
    """
    try:
        return {g.id for g in config.parse(yaml.safe_load(existing)).gates}
    except (config.ConfigError, yaml.YAMLError, AttributeError):
        import re

        return set(
            re.findall(
                r"^\s*-\s*id:\s*[\"']?([A-Za-z0-9][\w-]*)", existing, re.MULTILINE
            )
        )


def proposals(loaded: Spec, sidecar: Any = ()) -> tuple[config.Gate, ...]:
    """Every gate `wring plan` would propose: the spec's own block, then the
    sidecar's bindings.

    There are TWO sources and there always were — `wringer.spec.v1` has
    carried a `gates:` block since P2, and the sidecar is the channel that
    can additionally say which criterion a gate proves. The spec review
    caught that the collision between them was unspecified.

    **An id in both files is refused, never resolved.** Preferring either one
    silently would attach a drafted binding to a command the reader believes
    came from the other document, and the reader is the person about to
    install it by hand.
    """
    from_spec = {gate.id for gate in loaded.gates}
    clash = sorted(gate.id for gate in sidecar if gate.id in from_spec)
    if clash:
        named = ", ".join(f"'{gate_id}'" for gate_id in clash)
        raise SpecError(
            f"{GATESPEC_FILENAME} and {SPEC_FILENAME} both declare "
            f"{named}. One id, one definition: keep the binding in "
            f"{GATESPEC_FILENAME} and drop the entry from {SPEC_FILENAME}'s "
            "'gates:' block, or give one of them another id"
        )
    return (*loaded.gates, *sidecar)


def gate_diff(existing: str, proposed: Any) -> tuple[str, tuple[str, ...],
                                                     tuple[str, ...]]:
    """The change a human would have to make to `.wringer.yaml`, as a diff.

    Returns the diff text, the ids it would add, and the ids that already
    exist. Wringer prints this and stops: installing a gate is changing what
    "verified" means, and that is not a thing a drafter gets to do quietly.

    `proposed` is a sequence of gates rather than the `Spec` it used to be,
    because the sidecar is a second source and a binding cannot live on a
    `Spec` at all — `wringer.spec.v1` is frozen and `spec.parse` builds its
    gates with `allow_proves` off.
    """
    import difflib

    declared = declared_gate_ids(existing)
    fresh = tuple(g.id for g in proposed if g.id not in declared)
    already = tuple(g.id for g in proposed if g.id in declared)
    if not fresh:
        return "", fresh, already

    addition = []
    for gate in proposed:
        if gate.id not in fresh:
            continue
        addition += [f"  - id: {gate.id}", f"    run: {_scalar(gate.run)}"]
        if gate.timeout != config.DEFAULT_TIMEOUT_SECONDS:
            addition.append(f"    timeout: {gate.timeout}")
        if gate.optional:
            addition.append("    optional: true")
        if gate.proves:
            # The binding travels WITH the command, so one edit installs both
            # and nobody ends up with a gate whose purpose was left behind in
            # another file.
            addition.append(f"    proves: {gate.proves}")

    merged = _append_gates(existing, addition)
    if merged is None:
        # The change could not be expressed as an edit to this file without
        # risking a second `gates:` key — which YAML resolves by keeping the
        # LAST one, silently deleting every gate the repo already declared.
        # No diff is the honest answer; the caller prints the gates in words.
        return "", fresh, already

    before = existing.splitlines(keepends=True)
    proposed = merged.splitlines(keepends=True)
    # `a/` and `b/` so `git apply` accepts it as-is. The human is the intended
    # applier, but a diff a machine cannot apply is a diff nobody checked.
    diff = "".join(
        difflib.unified_diff(
            before,
            proposed,
            fromfile=f"a/{config.CONFIG_FILENAME}",
            tofile=f"b/{config.CONFIG_FILENAME}",
        )
    )
    return diff, fresh, already


def _append_gates(existing: str, addition: list[str]) -> str | None:
    """Put the new gates under the existing `gates:` key, or None if it cannot.

    Textual on purpose: a round-trip through a YAML dumper would reformat a
    file the human wrote, and a diff full of unrelated reflowing is a diff
    nobody reads.

    Returns **None** rather than appending a second `gates:` key when the
    existing one is not a block-style list — a flow-style `gates: [...]`, say.
    Two `gates:` keys is not a merge: YAML keeps the last, so the "purely
    additive" diff would delete every gate the repo already declared, and the
    reader would have applied it believing the opposite.
    """
    import re

    lines = existing.splitlines()
    block = "\n".join(addition)
    for index, line in enumerate(lines):
        if line.rstrip() != "gates:":
            continue
        end = index + 1
        while end < len(lines) and (
            not lines[end].strip() or lines[end].startswith((" ", "\t", "#"))
        ):
            end += 1
        # Back off over the blank lines that separate this block from the next
        # key, so the addition lands inside the gate list rather than pressed
        # up against whatever came after it.
        while end > index + 1 and not lines[end - 1].strip():
            end -= 1
        return "\n".join(lines[:end] + addition + lines[end:]) + "\n"

    if re.search(r"^gates\s*:", existing, re.MULTILINE):
        return None
    tail = "" if existing.endswith("\n") or not existing else "\n"
    return f"{existing}{tail}gates:\n{block}\n"


def tasks_file_is_generated(path: Path) -> bool:
    """Whether overwriting `tasks.jsonl` would destroy something else.

    There is no comment syntax in JSONL to leave a marker in, so the check is
    the real parser: a file every line of which is a task is a task file.
    """
    from wringer import fleet

    if not path.exists():
        return True
    try:
        fleet.load_tasks(path)
    except fleet.FleetError:
        return False
    return True


def brief_is_generated(path: Path) -> bool:
    return _carries(path, BRIEF_MARKER)


def rubric_is_generated(path: Path) -> bool:
    """A committed, hand-written rubric is not ours to replace.

    `judge.rubric:` has pointed at a file since v0.2, so a repo adopting
    `wring spec` may already have one — and it is the document that decides
    whether work is accepted.
    """
    return _carries(path, RUBRIC_MARKER)


def _carries(path: Path, marker: str) -> bool:
    if not path.exists():
        return True
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:300]
    except OSError:
        return False
    return marker in head


# --- the drafting bundle -------------------------------------------------


@dataclass(frozen=True)
class Bundle:
    """`.wringer/specs/<id>/`. Owns the redactor, so every write scrubs.

    The judge's shape, for the judge's reason: what would leave the machine is
    on disk before any socket opens, so it is auditable rather than asserted.
    """

    directory: Path
    spec_id: str
    started_at: datetime
    redactor: Redactor = Redactor()

    @classmethod
    def create(
        cls,
        specs_root: Path,
        now: datetime | None = None,
        redactor: Redactor | None = None,
    ) -> Bundle:
        started_at = now if now is not None else datetime.now().astimezone()
        try:
            specs_root.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            raise SpecError(f"cannot create {specs_root}: {exc}") from exc
        for _ in range(64):
            spec_id = evidence.new_run_id(started_at)
            directory = specs_root / spec_id
            try:
                directory.mkdir(exist_ok=False)
            except FileExistsError:
                continue
            except OSError as exc:
                raise SpecError(f"cannot create {directory}: {exc}") from exc
            return cls(directory, spec_id, started_at, redactor or Redactor())
        raise SpecError(f"could not allocate a directory under {specs_root}")

    def write_request(self, request: dict) -> Path:
        path = self.directory / REQUEST_FILENAME
        scrubbed = evidence.deep_scrub(self.redactor, request)
        path.write_text(json.dumps(scrubbed, indent=2) + "\n", encoding="utf-8")
        return path

    def write_response(self, body: Any) -> Path:
        path = self.directory / RESPONSE_FILENAME
        scrubbed = evidence.deep_scrub(self.redactor, body)
        path.write_text(json.dumps(scrubbed, indent=2) + "\n", encoding="utf-8")
        return path

    def write_summary(
        self, mode: str, prd: str, endpoint: str, model: str, drafted: Spec | None
    ) -> Path:
        lines = [
            f"# wring spec — {self.spec_id}",
            "",
            f"- mode: **{mode}**",
            f"- PRD: `{prd}`",
            f"- endpoint: `{self.redactor.scrub(endpoint)}`",
            f"- model: {model}",
        ]
        if drafted is None and mode == "dry_run":
            lines += [
                "",
                "Nothing was drafted: this was a dry run, so the request was "
                f"built and written to `{REQUEST_FILENAME}` and no socket was "
                "opened.",
            ]
        elif drafted is None:
            # A live run that produced nothing is NOT a dry run, and a summary
            # that said so would be a false claim in an evidence artifact.
            lines += [
                "",
                "**Nothing was drafted, and no spec file was written.** The "
                "request was sent and the exchange did not produce a usable "
                f"`{SCHEMA_VERSION}` document — see `{REQUEST_FILENAME}` and, "
                f"if a reply arrived at all, `{RESPONSE_FILENAME}`. The error "
                "is on the console.",
            ]
        else:
            lines += [
                f"- drafted: `{SPEC_FILENAME}` — **approved: false**",
                "",
                f"| {len(drafted.criteria)} criteria "
                f"| {len(drafted.gates)} gates "
                f"| {len(drafted.tasks)} tasks "
                f"| {len(drafted.questions)} open questions |",
                "|---|---|---|---|",
                "",
                f"Read `{SPEC_FILENAME}`, answer its open questions, and set "
                "`approved: true` by hand. Then run `wring plan`.",
            ]
        path = self.directory / SUMMARY_FILENAME
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path
