/** Generate from actual command help; optionally compare an extracted binary. */
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { commandHelp } from "../packages/cli/src/help";
import { runProcess } from "../packages/engine/src/process";
const root = resolve(import.meta.dir, ".."), output = resolve(root, "docs/CLI.md");
export const referenceCommands = ["", ...Object.keys(commandHelp), "setup", "runtime", "install", "assistant", "drive", "board", "headless", "figma-broker", "design", "experiment", "drive graph"];
export async function generateCliReference(launcher = [process.execPath, resolve(root, "packages/cli/src/launcher.ts")]) {
    const sections = [];
    for (const command of [...new Set(referenceCommands)]) {
        const result = await runProcess([...launcher, ...(command ? command.split(" ") : []), "--help"], { cwd: root, timeout: 15, maxBytes: 1024 * 1024 });
        if (result.exit_code || result.timed_out || result.stdout_truncated || !result.stdout.trim()) throw new Error(`Help could not be observed: ${command}`);
        sections.push(`## wring${command ? " " + command : ""}\n\n\`\`\`text\n${result.stdout.trim()}\n\`\`\``);
    }
    return `# CLI reference\n\nGenerated by scripts/cli-reference.ts from the executable help. Regenerate with\n\`bun scripts/cli-reference.ts\`; check an extracted candidate with\n\`bun scripts/cli-reference.ts --check /absolute/path/to/wring\`.\n\n## Exit codes\n\n| Code | Meaning |\n| --- | --- |\n| 0 | Command completed; a selected check pass may still be partial proof |\n| 1 | Check/audit failed |\n| 2 | Invalid invocation, policy/environment refusal or unavailable prerequisite |\n| 3 | Incomplete/unresolved state requiring inspection, including source/review mismatch |\n| 4 | Interrupted execution |\n\nRead the command's structured outcome with its exit code. Setup/read-only success\ndoes not approve a job; sending does not imply merge or deployment. Human pages\nand model-facing MCP have different permissions.\n\n${sections.join("\n\n")}\n`;
}
if (import.meta.main) {
    const args = process.argv.slice(2), check = args[0] === "--check", binary = check ? args[1] : undefined;
    if (args.length && (!check || args.length > 2)) throw new Error("Usage: bun scripts/cli-reference.ts [--check [ABSOLUTE_BINARY]]");
    const text = await generateCliReference(binary ? [resolve(binary)] : undefined);
    if (check) { if (await readFile(output, "utf8") !== text) throw new Error("CLI reference differs from executable help"); }
    else await writeFile(output, text);
    console.log(check ? "CLI reference matches executable help" : "Generated docs/CLI.md");
}
