/**
 * Types for every frozen record, generated from `schema/` — the one source
 * of truth for both languages.
 *
 * **Why generated and checked in (2026-09-06).** `schema/frozen.json` holds
 * a sha256 of every schema file, so a schema cannot move without a
 * deliberate act. If these types were hand-written they would be a second
 * description of the same shape and would drift the way every second
 * description in this repository has drifted; if they were generated at
 * build time they would not be reviewable in a diff. So they are generated
 * from the frozen files, checked in, and `--check` proves the checked-in
 * copy is what the schemas produce.
 *
 *   bun run scripts/generate-types.ts           # write
 *   bun run scripts/generate-types.ts --check   # refuse if it would change
 */
const HERE = new URL(".", import.meta.url).pathname;
const REPO = `${HERE}..`;
const SCHEMA_DIR = `${REPO}/schema`;
const OUT = `${HERE}../packages/records/src/generated.ts`;
type Schema = Record<string, any>;
/** A JSON Schema node as a TypeScript type, or `unknown` when it says nothing. */
function typeOf(node: Schema | undefined, indent: string): string {
    if (!node || typeof node !== "object")
        return "unknown";
    if (node.const !== undefined)
        return JSON.stringify(node.const);
    if (Array.isArray(node.enum)) {
        return node.enum.map((one: unknown) => JSON.stringify(one)).join(" | ");
    }
    if (Array.isArray(node.oneOf)) {
        return node.oneOf.map((one: Schema) => typeOf(one, indent)).join(" | ");
    }
    if (Array.isArray(node.anyOf)) {
        return node.anyOf.map((one: Schema) => typeOf(one, indent)).join(" | ");
    }
    const declared = node.type;
    if (Array.isArray(declared)) {
        return declared
            .map((one: string) => typeOf({ ...node, type: one }, indent))
            .join(" | ");
    }
    switch (declared) {
        case "string":
            return "string";
        case "integer":
        case "number":
            return "number";
        case "boolean":
            return "boolean";
        case "null":
            return "null";
        case "array":
            return `${typeOf(node.items, indent)}[]`;
        case "object":
            return objectType(node, indent);
        default:
            // A node with properties but no declared type is still an object here;
            // anything else says nothing this generator may invent a shape from.
            return node.properties ? objectType(node, indent) : "unknown";
    }
}
function objectType(node: Schema, indent: string): string {
    const properties: Schema = node.properties ?? {};
    const required = new Set<string>(node.required ?? []);
    const names = Object.keys(properties);
    const inner = `${indent}  `;
    const lines: string[] = [];
    for (const name of names) {
        const child = properties[name];
        const optional = required.has(name) ? "" : "?";
        const description = typeof child?.description === "string"
            ? `${inner}/** ${child.description.replace(/\s+/g, " ").trim()} */\n`
            : "";
        lines.push(`${description}${inner}${JSON.stringify(name)}${optional}: ${typeOf(child, inner)};`);
    }
    if (node.additionalProperties && typeof node.additionalProperties === "object") {
        lines.push(`${inner}[key: string]: ${typeOf(node.additionalProperties, inner)};`);
    }
    else if (node.additionalProperties !== false && names.length === 0) {
        return "Record<string, unknown>";
    }
    if (lines.length === 0)
        return "Record<string, never>";
    return `{\n${lines.join("\n")}\n${indent}}`;
}
/** `acceptance-v3.schema.json` -> `AcceptanceV3`. */
function typeNameOf(file: string): string {
    return file
        .replace(/\.schema\.json$/, "")
        .split(/[-_.]/)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join("");
}
const files = [...new Bun.Glob("*.schema.json").scanSync(SCHEMA_DIR)].sort();
if (files.length === 0)
    throw new Error(`no schemas under ${SCHEMA_DIR}`);
const blocks: string[] = [];
const versions: string[] = [];
const byName: string[] = [];
for (const file of files) {
    const schema: Schema = await Bun.file(`${SCHEMA_DIR}/${file}`).json();
    const name = typeNameOf(file);
    const title = typeof schema.title === "string" ? schema.title : file;
    const declared = schema.properties?.schema_version;
    const version: string | undefined = declared?.const;
    blocks.push(`/**\n * ${title}\n *\n * Generated from \`schema/${file}\`. Do not edit.\n */\nexport type ${name} = ${typeOf(schema, "")};\n`);
    byName.push(`  ${JSON.stringify(file)}: ${JSON.stringify(version ?? null)},`);
    if (version)
        versions.push(`  ${JSON.stringify(version)}: ${JSON.stringify(file)},`);
}
const body = `// GENERATED by scripts/generate-types.ts from schema/*.schema.json.
// Do not edit. Run \`bun run generate\` after a schema changes; CI runs
// \`--check\` and refuses a tree where this file is not what the schemas say.
//
// The schemas are frozen (\`schema/frozen.json\` holds a sha256 of each), so
// this file changing is always a deliberate act with a version behind it.

${blocks.join("\n")}
/** Every schema file, and the \`schema_version\` it fixes — null when it fixes none. */
export const SCHEMA_VERSIONS: Readonly<Record<string, string | null>> = Object.freeze({
${byName.join("\n")}
});

/** \`schema_version\` -> the schema file that claims it. */
export const SCHEMA_BY_VERSION: Readonly<Record<string, string>> = Object.freeze({
${versions.join("\n")}
});
`;
const wanted = Bun.argv.includes("--check");
const existing = (await Bun.file(OUT).exists()) ? await Bun.file(OUT).text() : "";
if (wanted) {
    if (existing !== body) {
        console.error("generate-types: the checked-in types are not what the schemas produce.\n" +
            "  A schema moved and the types did not, or the reverse. Run:\n" +
            "    bun run generate");
        process.exit(1);
    }
    console.log(`generate-types: ${files.length} schema(s), types are current`);
}
else {
    await Bun.write(OUT, body);
    console.log(`generate-types: ${files.length} schema(s) -> ${OUT}`);
}
