import { runReversions, type Reversion } from "./rebuild-reversions";
const job = "packages/application/src/verification-job.ts", pen = "packages/application/src/standalone-review.ts", delivery = "packages/delivery/src/deliver.ts", strict = "packages/engine/src/strict.ts", owner = "packages/cli/src/verification-owner.ts";
const cases: Reversion[] = [
    { name: "dirty-binary-edit", file: strict, before: ".filter(path => baseline[path] !== current[path])", after: ".filter(() => false)", test: "packages/engine/test/strict.test.ts", pattern: "already dirty binary" },
    { name: "head-movement", file: strict, before: 'if (before.head_sha !== after.head_sha) changed_tracked.push("HEAD");', after: "/* fault: HEAD movement ignored */", test: "packages/engine/test/strict.test.ts", pattern: "moved HEAD even" },
    { name: "display-source-binding", file: pen, before: "display.fingerprint !== snap.fingerprint || display.source_fingerprint !== sourceFingerprint", after: "false", test: "packages/application/test/standalone-review.test.ts", pattern: "stale second" },
    { name: "optional-acceptance-note", file: pen, before: '!options.by.trim() || options.by.length', after: '!options.by.trim() || !options.note?.trim() || options.by.length', test: "packages/application/test/standalone-review.test.ts", pattern: "no invented note" },
    { name: "finite-repetitions", file: job, before: "remaining.repetitions > 0 &&", after: "", test: "packages/application/test/verification-job.test.ts", pattern: "finite operator grant" },
    { name: "check-input-binding", file: job, before: "policy.configSha256 === job.configSha256 && hashValue(policy.checkIdentities) === hashValue(job.checkIdentities)", after: "policy.configSha256 === job.configSha256", test: "packages/application/test/verification-job.test.ts", pattern: "changing check inputs" },
    { name: "result-source-binding", file: job, before: "source.fingerprint === latest.observation.source.fingerprint &&", after: "", test: "packages/application/test/verification-job.test.ts", pattern: "changing check inputs" },
    { name: "stopped-approval", file: job, before: 'if (await assistantExists(root, jobPath(id, "stop.json"))) throw new Error("This job was stopped; approval cannot restore its execution authority");', after: "/* fault: approval resurrects stopped work */", test: "packages/application/test/verification-job.test.ts", pattern: "stopped verification" },
    { name: "read-only-git-inspection", file: "packages/engine/src/git.ts", before: ', "-c", "core.fsmonitor=false"', after: "", test: "packages/application/test/verification-job.test.ts", pattern: "fsmonitor" },
    { name: "public-wait-signal", file: "packages/application/src/assistant.ts", before: "=> call(token, name, raw, signal), runner", after: "=> call(token, name, raw), runner", test: "packages/application/test/assistant.test.ts", pattern: "public service wait" },
    { name: "exact-display-set", file: owner, before: 'action === "decision" && (!Array.isArray(body.displayIds)', after: 'false && (!Array.isArray(body.displayIds)', test: "packages/cli/test/verification-owner.test.ts", pattern: "empty-note acceptance" },
    { name: "stale-cancellation", file: job, before: "current.revision !== request.expectedRevision || current.candidateIdentity !== request.expectedCandidateIdentity", after: "false", test: "packages/cli/test/verification-owner.test.ts", pattern: "lost run reply" },
    { name: "visible-stop", file: "packages/board/src/job-render.ts", before: 'id="stop-job" class="secondary"', after: 'id="removed-stop-job" class="secondary"', test: "packages/cli/test/verification-owner.test.ts", pattern: "visible Stop" },
    { name: "stale-negative-verdict", file: owner, before: 'row.judgement?.verdict === "not_met" && !row.judgement.stale', after: 'row.judgement?.verdict === "not_met"', test: "packages/cli/test/verification-owner.test.ts", pattern: "correction preserves" },
    { name: "retained-publication", file: owner, before: 'quote(value.publication.expected.remoteURL)', after: 'quote(value.prepared!.expected.remoteURL)', test: "packages/cli/test/verification-owner.test.ts", pattern: "T10 verification review" },
    ...["fingerprint", "tree", "remoteURL", "baseCommit"].map(key => ({ name: `prepared-${key}`, file: delivery, before: `if (options.expected && ${key === "fingerprint" ? "before.fingerprint" : key === "baseCommit" ? "base" : key} !== options.expected.${key})`, after: "if (false)", test: "packages/delivery/test/delivery.test.ts", pattern: `changed prepared ${key}` })),
];
await runReversions("m2", ["packages/engine/test/strict.test.ts", "packages/application/test/standalone-review.test.ts", "packages/application/test/verification-job.test.ts", "packages/application/test/assistant.test.ts", "packages/cli/test/verification-owner.test.ts", "packages/cli/test/assistant-job.test.ts", "packages/delivery/test/delivery.test.ts"], cases);
