import { runReversions } from "./rebuild-reversions";
const assistant = "packages/application/src/assistant.ts", assistantTest = "packages/application/test/assistant.test.ts", composition = "packages/application/src/proposal-composition.ts", compositionTest = "packages/application/test/proposal-composition.test.ts", revisionTest = "packages/application/test/proposal-revision.test.ts", protocol = "packages/application/src/delegation-protocol.ts", protocolTest = "packages/application/test/delegation-protocol.test.ts", owner = "packages/cli/src/delegation-owner.ts", ownerTest = "packages/cli/test/delegation-owner.test.ts";
await runReversions("m4-joins", [assistantTest, compositionTest, revisionTest, protocolTest, ownerTest, "packages/cli/test/assistant-job.test.ts"], [
    { name: "pm-observation-join", file: assistant, before: "decision?.observedRevision !== undefined &&", after: "false &&", test: assistantTest, pattern: "later PM observation" },
    { name: "question-digest", file: composition, before: "hashValue({ profileIdentity: profile.plan_sha256, proposal: input })", after: "hashValue({ profileIdentity: profile.plan_sha256, intent: (input as any).intent })", test: compositionTest, pattern: "question-only draft" },
    { name: "question-ceilings", file: composition, before: "const questionOnly = input.criteria === undefined && input.checks === undefined && questions.length > 0;", after: "const questionOnly = input.criteria === undefined && input.checks === undefined && questions.length > 0; if (questionOnly) return result(null, assumptions, questions);", test: compositionTest, pattern: "question-only draft" },
    { name: "page-action-actor", file: protocol, before: 'code: phase, actor: "operator"', after: 'code: phase, actor: "assistant"', test: protocolTest, pattern: "ready page phase" },
    { name: "independent-destination", file: assistant, before: 'sourceBranch: `${workspace.destination.sourceBranch}/${current.id}`', after: "sourceBranch: workspace.destination.sourceBranch", test: revisionTest, pattern: "independent jobs" },
    { name: "validation-no-allocation", file: owner, before: "const { args } = parseDelegationCall(name, raw);", after: 'const { args } = parseDelegationCall(name, raw); if (name === "wringer.validate_proposal") await writeFile(join(ownerRoot, "injected-read-effect"), "fixture-only mutation");', test: ownerTest, pattern: "registered delegation joins" },
]);
